export default {
    abbreviations: {
        "NLG": "Nose landing gear",
        "MLG": "Main landing gear",
        "MP-RTIP": "Multi-platform radar technology insertion program",
        "LCS": "Liquid cooling system",
        "ECS": "Engine cooling system",
        "UHF": "Ultra-high frequency",
        "V/UHF": "Very high frequency/Ultra-high frequency",
        "LOS": "Line of sight",
        "IFF": "Identification, friend or foe",
        "ELT": "Emergency locator transmitter",
        "ARPA": "Advanced Research Projects Agency",
        "ILS": "Instrument landing system",
        "GPS": "Global Positioning System",
        "PCU": "Power control unit",
        "WB": "Wide-band",
        "WBDL": "Wide-band data link",
        "SCAT-1": "Special Category I",
        "GATM": "Global air traffic management",
        "DC": "Direct current",
        "AC": "Alternate current",
        "IMMC": "Integrated Mission Management Computer",
        "HVPS": "High Volume Precipitation Spectrometer",
        "TCAS": "Traffic collision avoidance system",
        "HPA": "High-power amplifier",
        "LNA": "Low-noise amplifier",
        "AICS": "Airborne Integrated Communication System",
        "HAIPE": "High Assurance Internet Protocol Encryptor",
        "VOIP": "Voice over Internet Protocol",
        "ADMS": "Advanced Distribution Management System",
        "SIU": "System interface unit",
        "TU": "Transceiver unit",
        "DS": "Data server",
        "RDS": "Remote data store",
        "SAU": "Steerable antenna unit",
        "ACU": "Antenna control unit",
        "FEU": "Front-end unit",
        "OAU": "Omnidirectional antenna unit",
        "RPS": "Remote power supply",
        "ESM/RWR": "Electronic Support Measures/Radar Warning Receiver",
        "AAIU": "Azimuth antenna interferometer unit",
        "LRU": "Line-replaceable unit",
        "HPA": "High-power amplifier",
        "RPU": "Receiver processing unit",
        "AIS": "Automatic identification system",
        "FADEC": "Full authority digital engine control",
        "Satcom": "Satellite communication"
    }
}
